# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 945ae28f51eb2d45d767d216da74e56c33ded00d2810bf59e1eabf62d557b94debb6426f609cdf30b3620e89da7be7ee773eb0d86fdcb5beccf0fc2e2111be08

test:
  secret_key_base: 137a67c4abd492ade895f63ffaacc90e4b3509ff3b5e98568d4ff7187194075f0bad52df8107af6a5d04337f58803b5c942a89989867a36c57d042e954d1c524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
